trigger:
- main

pool: Default

steps:
- script: |
    cd $HOME
    echo "$PWD"
    source env/bin/activate
    az login --use-device-code
  displayName: Login Azure
  
- script: |
    cd $HOME
    source env/bin/activate
    chmod +x $(System.DefaultWorkingDirectory)/new-file.sh
    $(System.DefaultWorkingDirectory)/new-file.sh $(RESOURCE_GROUP) start
  displayName: Executing
