trigger:
- main

pool: Default

steps:
- script: |
    cd $HOME
    echo "$PWD"
    source env/bin/activate
    az login --use-device-code
  displayName: Login Azure
- task: Bash@3
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/new-file.sh'
    arguments: $(RESOURCE_GROUP) stop
  displayName: Script